channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=25.0.1
- pip:
  - mlflow==2.22.0
  - astunparse==1.6.3
  - cloudpickle==3.1.1
  - dill==0.3.8
  - numpy==1.23.5
  - pandas==2.2.3
  - pydot==3.0.4
  - torch==2.7.0
  - tqdm==4.67.1
name: mlflow-env
